Потренируемся самостоятельно писать многослойный перцептрон для работы с текстами.

Возьмем для этого датасет про юридические тексты. В этом датасете есть описания дел, а в качестве цп - то, что с делами произошло.

In [1]:
!wget https://raw.githubusercontent.com/rsuh-python/mag2022/main/CL/term02/06-Embeddings/legal_text_classification.csv

--2025-03-27 01:58:07--  https://raw.githubusercontent.com/rsuh-python/mag2022/main/CL/term02/06-Embeddings/legal_text_classification.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 68202412 (65M) [text/plain]
Saving to: ‘legal_text_classification.csv’

legal_text_classifi 100%[===================>]  65.04M   132MB/s    in 0.5s

2025-03-27 01:58:08 (132 MB/s) - ‘legal_text_classification.csv’ saved [68202412/68202412]

Для начала напишем бейзлайн - логистическую регрессию. Возьмем в качестве признаков только текст - описание самого дела (case_text). Целевую переменную, очевидно, нужно превратить в чиселки (OHE).

- проверьте данные на пропуски
- проверьте баланс классов - это очень важно!
- используйте TF-IDF
- не забудьте использовать LabelEncoder
- логистической регрессии может понадобиться выставить solver='liblinear'
- если не помните, как работать с несбалансированными датасетами, просмотрите наши конспекты - точно где-то было (на худой конец документация к логрегу)

In [2]:
import pandas as pd

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder

In [3]:
data = pd.read_csv('legal_text_classification.csv')
data.head()

,case_id,case_outcome,case_title,case_text
0,Case1,cited,Alpine Hardwood (Aust) Pty Ltd v Hardys Pty Lt...,Ordinarily that discretion will be exercised s...
1,Case2,cited,Black v Lipovac [1998] FCA 699 ; (1998) 217 AL...,The general principles governing the exercise ...
2,Case3,cited,Colgate Palmolive Co v Cussons Pty Ltd (1993) ...,Ordinarily that discretion will be exercised s...
3,Case4,cited,Dais Studio Pty Ltd v Bullett Creative Pty Ltd...,The general principles governing the exercise ...
4,Case5,cited,Dr Martens Australia Pty Ltd v Figgins Holding...,The preceding general principles inform the ex...

In [ ]:
data.isna ()

       case_id  case_outcome  case_title  case_text
0        False         False       False      False
1        False         False       False      False
2        False         False       False      False
3        False         False       False      False
4        False         False       False      False
...        ...           ...         ...        ...
24980    False         False       False      False
24981    False         False       False      False
24982    False         False       False      False
24983    False         False       False      False
24984    False         False       False      False

[24985 rows x 4 columns]

In [4]:
data.dropna ()
data.isna ()

       case_id  case_outcome  case_title  case_text
0        False         False       False      False
1        False         False       False      False
2        False         False       False      False
3        False         False       False      False
4        False         False       False      False
...        ...           ...         ...        ...
24980    False         False       False      False
24981    False         False       False      False
24982    False         False       False      False
24983    False         False       False      False
24984    False         False       False      False

[24985 rows x 4 columns]

In [5]:
data.case_outcome.unique()

array(['cited', 'applied', 'followed', 'referred to', 'related',
       'considered', 'discussed', 'distinguished', 'affirmed', 'approved'],
      dtype=object)

In [6]:
data.case_outcome.value_counts()

case_outcome
cited            12219
referred to       4384
applied           2448
followed          2256
considered        1712
discussed         1024
distinguished      608
related            113
affirmed           113
approved           108
Name: count, dtype: int64

In [7]:
data.drop(['case_title', 'case_id'], axis=1, inplace=True)
label_encoder = LabelEncoder()
data.case_outcome = label_encoder.fit_transform(data.case_outcome)

In [8]:
data.head ()

   case_outcome                                          case_text
0             3  Ordinarily that discretion will be exercised s...
1             3  The general principles governing the exercise ...
2             3  Ordinarily that discretion will be exercised s...
3             3  The general principles governing the exercise ...
4             3  The preceding general principles inform the ex...

In [9]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)
encoded_features = encoder.fit_transform(data[['case_outcome']])
encoded_df = pd.DataFrame(encoded_features).astype (int)
df_final = pd.concat([data.drop(columns=['case_outcome']), encoded_df], axis=1)

df_final.head ()

,case_text,0,1,2,3,4,5,6,7,8,9
0,Ordinarily that discretion will be exercised s...,0,0,0,1,0,0,0,0,0,0
1,The general principles governing the exercise ...,0,0,0,1,0,0,0,0,0,0
2,Ordinarily that discretion will be exercised s...,0,0,0,1,0,0,0,0,0,0
3,The general principles governing the exercise ...,0,0,0,1,0,0,0,0,0,0
4,The preceding general principles inform the ex...,0,0,0,1,0,0,0,0,0,0

In [10]:
df_final1 = pd.concat ([data['case_outcome'], df_final], axis=1)
df_final1.head ()

,case_outcome,case_text,0,1,2,3,4,5,6,7,8,9
0,3,Ordinarily that discretion will be exercised s...,0,0,0,1,0,0,0,0,0,0
1,3,The general principles governing the exercise ...,0,0,0,1,0,0,0,0,0,0
2,3,Ordinarily that discretion will be exercised s...,0,0,0,1,0,0,0,0,0,0
3,3,The general principles governing the exercise ...,0,0,0,1,0,0,0,0,0,0
4,3,The preceding general principles inform the ex...,0,0,0,1,0,0,0,0,0,0

In [11]:
data.head ()

   case_outcome                                          case_text
0             3  Ordinarily that discretion will be exercised s...
1             3  The general principles governing the exercise ...
2             3  Ordinarily that discretion will be exercised s...
3             3  The general principles governing the exercise ...
4             3  The preceding general principles inform the ex...

In [12]:
X = data['case_text']
y = data['case_outcome']

In [13]:
data.dropna ()
data['case_text'] = data.astype(str).agg(''.join, axis=1)

In [14]:
print(data.isna().sum())

case_outcome    0
case_text       0
dtype: int64

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

vect = TfidfVectorizer()
X_train1 = vect.fit_transform(X_train.values.astype('U'))
X_test1 = vect.transform(X_test.values.astype('U'))


model = LogisticRegression(solver='liblinear', class_weight='balanced')
model.fit(X_train1, y_train)

LogisticRegression(class_weight='balanced', solver='liblinear')

In [16]:
y_pred = model.predict (X_test1)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.24      0.69      0.35        32
           1       0.32      0.25      0.28       515
           2       0.11      0.32      0.17        19
           3       0.68      0.67      0.68      2457
           4       0.27      0.29      0.28       324
           5       0.19      0.34      0.24       205
           6       0.26      0.55      0.35       122
           7       0.34      0.27      0.30       436
           8       0.55      0.40      0.46       859
           9       0.26      0.54      0.35        28

    accuracy                           0.50      4997
   macro avg       0.32      0.43      0.35      4997
weighted avg       0.53      0.50      0.51      4997


Если все сделали как я, должна получиться средняя f-score в районе 0.5.

Теперь давайте попробуем написать нейронную сетку по аналогии с тетрадкой про твиттер из прошлого семинара.

In [17]:
import numpy as np
from string import punctuation
from collections import Counter
from sklearn.utils import shuffle, class_weight

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, RandomSampler, SequentialSampler
from torch.nn.utils.rnn import pad_sequence
import torch.optim as optim

class_weight - очень полезная для нас штука. Можно вычислить веса классов автоматически с ее помощью:

In [18]:
# первый аргумент - какие веса высчитывать, второй - какие у нас классы, третий - какие их частоты
yweights = class_weight.compute_class_weight('balanced', classes=np.unique(data.case_outcome), y=data.case_outcome)

Заметьте, что возвращает оно np.array.

Нужно написать:

- функцию для предобработки текста, которая получает сырой текст и возвращает список токенов
- создать словарь word2id
- и обратный ему id2word

In [19]:
def preprocess(text):
    tokens = text.lower().split()
    tokens = [token.strip(punctuation) for token in tokens]
    return tokens

from collections import Counter

vocab = Counter()

for text in data['case_text']:
    vocab.update(preprocess(text))
print('всего уникальных токенов:', len(vocab))

word2id = {'PAD': 0}

for word in vocab:
    word2id[word] = len(word2id)

id2word = {i: word for word, i in word2id.items()}

всего уникальных токенов: 67014

Лучше это все, конечно, запускать в колабе... не забудьте там выбрать T4 GPU в рантайме

In [20]:
DEVICE = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
DEVICE

device(type='cuda')

Нужно написать класс для нашего датасета (можно беспощадно копипастить из тетрадки про твиттер)

In [21]:
class LegalDataset(Dataset):

    def __init__(self, dataset, word2id, DEVICE):
        self.dataset = dataset['text'].values
        self.word2id = word2id
        self.length = dataset.shape[0]
        self.target = dataset['tone'].values
        self.device = DEVICE

    def __len__(self): #это обязательный метод, он должен уметь считать длину датасета
        return self.length

    def __getitem__(self, index): #еще один обязательный метод. По индексу возвращает элемент выборки
        tokens = self.preprocess(self.dataset[index]) # токенизируем
        ids = torch.LongTensor([self.word2id[token] for token in tokens if token in self.word2id])
        y = [self.target[index]]
        return ids, y

    def preprocess(self, text):
        tokens = text.lower().split()
        tokens = [token.strip(punctuation) for token in tokens]
        tokens = [token for token in tokens if token]
        return tokens

    def collate_fn(self, batch): #этот метод можно реализовывать и отдельно,
    # он понадобится для DataLoader во время итерации по батчам
      ids, y = list(zip(*batch))
      padded_ids = pad_sequence(ids, batch_first=True).to(self.device)
      #мы хотим применять BCELoss, он будет брать на вход predicted размера batch_size x 1
      #(так как для каждого семпла модель будет отдавать одно число), target размера batch_size x 1
      y = torch.Tensor(y).to(self.device) # tuple ([1], [0], [1])  -> Tensor [[1.], [0.], [1.]]
      return padded_ids, y

In [22]:
train_sentences, val_sentences = train_test_split(data['case_text'], test_size=0.2)

In [23]:
print (train_sentences)

14215    4In the context of operations in overseas terr...
9147     3In Re Australian Elizabethan Theatre Trust; L...
20446    8The respondent stressed that the course taken...
24122    8As I have noted earlier, Div 7 of Pt VIB prov...
2134     3I accept the submission made by counsel for t...
                               ...
10996    8Support for the view that a distinction is to...
672      7Tribunal saw the issue between the parties as...
11304    3The reasonable anticipation test is not a que...
22457    3No doubt, many descriptions of the purpose of...
12223    8a cause of action may be viable in the United...
Name: case_text, Length: 19988, dtype: object

In [29]:
word2id.update({'<UNK>': -1})

In [32]:
def text_to_ids(text, word2id, max_len=6):
    tokens = text.lower().split()
    ids = [word2id.get(t, word2id["<UNK>"]) for t in tokens]
    ids = ids[:max_len] + [0] * (max_len - len(ids))
    return ids

max_len = 90

data_copy = data

data_copy["ids"] = data_copy["case_text"].apply(lambda t: text_to_ids(t, word2id, max_len=max_len))

id_cols = data_copy["ids"].apply(pd.Series)
id_cols.columns = [f"tok_{i+1}" for i in id_cols.columns]

big_df = pd.concat([data_copy, id_cols], axis=1).drop(columns=["ids"])
big_df.head ()

,case_outcome,case_text,tok_1,tok_2,tok_3,tok_4,tok_5,tok_6,tok_7,tok_8,...,tok_81,tok_82,tok_83,tok_84,tok_85,tok_86,tok_87,tok_88,tok_89,tok_90
0,3,3Ordinarily that discretion will be exercised ...,1,2,3,4,5,6,7,2,...,0,0,0,0,0,0,0,0,0,0
1,3,3The general principles governing the exercise...,65,66,67,68,10,69,70,10,...,110,37,38,39,111,112,37,38,-1,44
2,3,3Ordinarily that discretion will be exercised ...,1,2,3,4,5,6,7,2,...,0,0,0,0,0,0,0,0,0,0
3,3,3The general principles governing the exercise...,65,66,67,68,10,69,70,10,...,110,37,38,39,111,112,37,38,-1,44
4,3,3The preceding general principles inform the e...,65,147,66,67,148,10,69,70,...,2,16,181,182,5,-1,10,177,184,10

In [36]:
big_df_copy = big_df
big_df_copy = big_df_copy.drop (columns=["case_text"])

In [37]:
train_sentences, val_sentences = train_test_split(big_df_copy.drop (columns=["case_outcome"]), test_size=0.2)

In [38]:
train_sentences.head ()

,tok_1,tok_2,tok_3,tok_4,tok_5,tok_6,tok_7,tok_8,tok_9,tok_10,...,tok_81,tok_82,tok_83,tok_84,tok_85,tok_86,tok_87,tok_88,tok_89,tok_90
3727,-1,10,84,1977,2,551,23920,656,12,1522,...,1272,61,-1,5752,53,232,16,427,102,10576
4123,1000,722,29,3581,182,102,265,10,7504,119,...,2,119,98,204,3581,-1,32,368,868,204
23922,6658,-1,2193,135,2192,15,10,1248,70,6468,...,-1,901,61,-1,1714,50,999,10,316,70
18814,1000,1093,106,5,3280,235,-1,-1,-1,325,...,23,74,452,-1,185,161,8998,-1,161,-1
23413,65001,70,2765,10062,32,452,268,135,1440,73,...,185,4536,50,1657,852,699,12,1723,-1,12

In [40]:
train_sampler = RandomSampler(train_sentences)
train_iterator = DataLoader(train_sentences, sampler=train_sampler, batch_size=1024)

In [43]:
val_sampler = RandomSampler(val_sentences)
val_iterator = DataLoader(val_sentences, sampler=val_sampler, batch_size=1024)

In [84]:
X_train = val_sentences
X_test = val_sentences
y_train, y_test = train_test_split(y, test_size=0.2)

In [57]:
from sklearn.preprocessing import StandardScaler

X = big_df_copy.drop (columns=["case_outcome"])
y = big_df_copy["case_outcome"]

y.head ()

0    3
1    3
2    3
3    3
4    3
Name: case_outcome, dtype: int64

In [82]:
y = y.astype(int)

In [58]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [59]:
X_train, X_test = train_test_split(X_scaled, test_size=0.2)

In [99]:
from torch.utils.data import TensorDataset, DataLoader

X_tensor = torch.tensor(X_train, dtype=torch.float32)
y_tensor = torch.tensor(y_train, dtype=torch.float32)

dataset = TensorDataset(X_tensor, y_tensor)
train_loader = DataLoader(dataset, batch_size=512, shuffle=True)

ValueError: could not determine the shape of object type 'DataFrame'

Ну и наконец напишем архитектуру. Модель при инициализации должна принимать размер словаря и эмбеддинга. У нас в датасете 10 классов, поэтому, в отличие от тетрадки про твиттер, нужно использовать Softmax и возвращать вероятности классов. В качестве лосса подойдет кросс-энтропия (я ее уже за вас вписала вместе с весами классов).

In [52]:
import torch
import torch.nn as nn
import torch.nn.functional as F

num_classes = 10
input_dim = 90
learning_rate = 0.01
epochs = 100


class MLP (nn.Module):
    def __init__(self, input_dim, num_classes, hidden_dim=128):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, num_classes)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        logits = self.fc2(x)
        probs = F.softmax(logits, dim=1)
        return probs

In [54]:
model = MLP(input_dim, num_classes)
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

Теперь нужно написать трейнлуп (лучше скопипастить откуда-нибудь), инициализировать нашу модель и запустить)

In [97]:
def train(model, train_loader, val_loader, optimizer, device, class_weights, epochs):
    model.to(device)


    if class_weights is not None:
        class_weights = class_weights.to(device)
        loss_fn = torch.nn.CrossEntropyLoss(weight=class_weights)
    else:
        loss_fn = torch.nn.CrossEntropyLoss()

    for epoch in range(epochs):
        model.train()
        total_loss = 0
        correct = 0
        total = 0

        for X, y in train_loader:
            X, y = X.to(device), y.to(device)
            y = y.long ()

            optimizer.zero_grad()
            logits = model(X)
            loss = loss_fn(logits, y)
            loss.backward()
            optimizer.step()

            total_loss += loss.item() * X.size(0)
            preds = logits.argmax(dim=1)
            correct += (preds == y).sum().item()
            total += y.size(0)

        avg_loss = total_loss / total
        acc = correct / total * 100
        print(f"[Epoch {epoch+1}] Loss: {avg_loss:.4f} | Acc: {acc:.2f}%")

        if val_loader is not None:
            model.eval()
            val_loss = 0
            val_correct = 0
            val_total = 0
            with torch.no_grad():
                for X_val, y_val in val_loader:
                    y_val = y_val.long ()
                    X_val, y_val = X_val.to(device), y_val.to(device)
                    logits = model(X_val)
                    loss = loss_fn(logits, y_val)
                    val_loss += loss.item() * X_val.size(0)
                    val_correct += (logits.argmax(dim=1) == y_val).sum().item()
                    val_total += y_val.size(0)

            val_loss /= val_total
            val_acc = val_correct / val_total * 100
            print(f"           Val Loss: {val_loss:.4f} | Acc: {val_acc:.2f}%")

In [64]:
X_test

,tok_1,tok_2,tok_3,tok_4,tok_5,tok_6,tok_7,tok_8,tok_9,tok_10,...,tok_81,tok_82,tok_83,tok_84,tok_85,tok_86,tok_87,tok_88,tok_89,tok_90
10282,13952,10,450,70,10,1032,135,98,1999,70,...,893,98,2838,2,16,883,23,1474,16,228
11530,6019,13,50,529,2900,1891,15,10,635,180,...,70,10,139,102,265,10,471,119,-1,2250
23091,1799,180,23,16914,119,1895,73,10,770,5373,...,105,119,351,119,98,-1,117,243,97,98
23904,11255,67,13,2444,32,103,33,119,609,20,...,0,0,0,0,0,0,0,0,0,0
16315,1718,-1,16,83,84,249,598,32,16346,39,...,2153,20,1632,235,23,948,92,1372,1603,129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16182,65,207,2102,-1,3906,-1,280,13,4409,1633,...,6493,39,52685,-1,1059,48,9237,50,8918,-1
22370,63586,224,70,103,84,2102,2,1093,2,13,...,1004,630,271,1069,10,5783,84,97,98,291
16409,11662,10,569,10,67,325,265,289,135,3074,...,13,246,273,2036,70,252,12,268,828,52938
13164,1555,1158,5342,3940,57,38,-1,939,845,-1,...,119,3633,2,615,678,608,32,5618,-1,235
24879,66938,4017,2,902,971,13,1837,440,73,10,...,2,122,5,1069,10,2181,1369,265,270,131

In [65]:
X_test_tensor = torch.tensor(X_test.values, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32)

dataset2 = TensorDataset(X_test_tensor, y_test_tensor)
val_loader = DataLoader(dataset, batch_size=512, shuffle=True)

In [80]:
yweights_tensor = torch.from_numpy(yweights).float().to(device)

In [78]:
print (yweights)

[22.11061947  1.02062908 23.13425926  0.20447663  1.45940421  2.43994141
  4.109375    1.10749113  0.56991332 22.11061947]

In [98]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

train (model, train_loader, val_loader, optimizer, device, yweights_tensor, epochs)

[Epoch 1] Loss: 2.2317 | Acc: 9.48%
           Val Loss: 2.1843 | Acc: 9.09%
[Epoch 2] Loss: 2.2028 | Acc: 9.70%
           Val Loss: 2.1664 | Acc: 9.86%
[Epoch 3] Loss: 2.1656 | Acc: 11.29%
           Val Loss: 2.1372 | Acc: 13.68%
[Epoch 4] Loss: 2.1438 | Acc: 12.96%
           Val Loss: 2.1171 | Acc: 13.89%
[Epoch 5] Loss: 2.1229 | Acc: 14.09%
           Val Loss: 2.0974 | Acc: 16.02%
[Epoch 6] Loss: 2.1111 | Acc: 15.31%
           Val Loss: 2.0892 | Acc: 14.66%
[Epoch 7] Loss: 2.1136 | Acc: 15.03%
           Val Loss: 2.0882 | Acc: 14.88%
[Epoch 8] Loss: 2.0920 | Acc: 16.17%
           Val Loss: 2.0767 | Acc: 14.63%
[Epoch 9] Loss: 2.0882 | Acc: 17.45%
           Val Loss: 2.0662 | Acc: 18.61%
[Epoch 10] Loss: 2.0797 | Acc: 16.71%
           Val Loss: 2.0561 | Acc: 20.40%
[Epoch 11] Loss: 2.0722 | Acc: 18.30%
           Val Loss: 2.0600 | Acc: 21.31%
[Epoch 12] Loss: 2.0617 | Acc: 19.59%
           Val Loss: 2.0481 | Acc: 17.62%
[Epoch 13] Loss: 2.0682 | Acc: 17.21%
           Val Loss: 2.0468 | Acc: 19.66%
[Epoch 14] Loss: 2.0563 | Acc: 18.43%
           Val Loss: 2.0369 | Acc: 21.34%
[Epoch 15] Loss: 2.0396 | Acc: 20.62%
           Val Loss: 2.0240 | Acc: 21.72%
[Epoch 16] Loss: 2.0292 | Acc: 21.50%
           Val Loss: 2.0193 | Acc: 20.56%
[Epoch 17] Loss: 2.0388 | Acc: 19.79%
           Val Loss: 2.0199 | Acc: 21.77%
[Epoch 18] Loss: 2.0412 | Acc: 21.04%
           Val Loss: 2.0243 | Acc: 22.29%
[Epoch 19] Loss: 2.0333 | Acc: 20.95%
           Val Loss: 2.0177 | Acc: 22.13%
[Epoch 20] Loss: 2.0318 | Acc: 21.46%
           Val Loss: 2.0227 | Acc: 22.53%
[Epoch 21] Loss: 2.0325 | Acc: 21.85%
           Val Loss: 2.0138 | Acc: 21.74%
[Epoch 22] Loss: 2.0270 | Acc: 20.97%
           Val Loss: 2.0202 | Acc: 20.76%
[Epoch 23] Loss: 2.0283 | Acc: 21.72%
           Val Loss: 2.0213 | Acc: 22.09%
[Epoch 24] Loss: 2.0272 | Acc: 22.06%
           Val Loss: 2.0085 | Acc: 22.94%
[Epoch 25] Loss: 2.0158 | Acc: 22.70%
           Val Loss: 2.0097 | Acc: 19.08%
[Epoch 26] Loss: 2.0339 | Acc: 18.81%
           Val Loss: 2.0144 | Acc: 22.79%
[Epoch 27] Loss: 2.0343 | Acc: 22.12%
           Val Loss: 2.0234 | Acc: 20.07%
[Epoch 28] Loss: 2.0215 | Acc: 22.51%
           Val Loss: 2.0041 | Acc: 26.10%
[Epoch 29] Loss: 2.0079 | Acc: 23.46%
           Val Loss: 1.9966 | Acc: 26.68%
[Epoch 30] Loss: 2.0004 | Acc: 25.11%
           Val Loss: 1.9880 | Acc: 26.48%
[Epoch 31] Loss: 1.9963 | Acc: 25.67%
           Val Loss: 1.9885 | Acc: 27.54%
[Epoch 32] Loss: 1.9897 | Acc: 25.99%
           Val Loss: 1.9826 | Acc: 27.09%
[Epoch 33] Loss: 1.9857 | Acc: 26.84%
           Val Loss: 1.9739 | Acc: 28.21%
[Epoch 34] Loss: 1.9820 | Acc: 27.13%
           Val Loss: 1.9719 | Acc: 29.26%
[Epoch 35] Loss: 1.9788 | Acc: 28.14%
           Val Loss: 1.9705 | Acc: 28.70%
[Epoch 36] Loss: 1.9835 | Acc: 27.14%
           Val Loss: 1.9781 | Acc: 27.83%
[Epoch 37] Loss: 1.9945 | Acc: 26.22%
           Val Loss: 1.9897 | Acc: 25.90%
[Epoch 38] Loss: 2.0012 | Acc: 23.99%
           Val Loss: 1.9846 | Acc: 25.30%
[Epoch 39] Loss: 1.9975 | Acc: 24.11%
           Val Loss: 1.9831 | Acc: 26.18%
[Epoch 40] Loss: 1.9914 | Acc: 25.53%
           Val Loss: 1.9827 | Acc: 24.92%
[Epoch 41] Loss: 1.9860 | Acc: 25.59%
           Val Loss: 1.9820 | Acc: 26.21%
[Epoch 42] Loss: 1.9853 | Acc: 27.02%
           Val Loss: 1.9764 | Acc: 26.36%
[Epoch 43] Loss: 1.9864 | Acc: 26.72%
           Val Loss: 1.9756 | Acc: 26.86%
[Epoch 44] Loss: 2.0102 | Acc: 23.12%
           Val Loss: 1.9961 | Acc: 24.78%
[Epoch 45] Loss: 2.0071 | Acc: 24.02%
           Val Loss: 1.9938 | Acc: 24.54%
[Epoch 46] Loss: 1.9976 | Acc: 24.15%
           Val Loss: 1.9830 | Acc: 25.83%
[Epoch 47] Loss: 1.9861 | Acc: 26.40%
           Val Loss: 1.9768 | Acc: 27.33%
[Epoch 48] Loss: 1.9790 | Acc: 27.40%
           Val Loss: 1.9708 | Acc: 27.82%
[Epoch 49] Loss: 1.9768 | Acc: 27.11%
           Val Loss: 1.9645 | Acc: 28.97%
[Epoch 50] Loss: 1.9785 | Acc: 26.63%
           Val Loss: 1.9707 | Acc: 27.72%
[Epoch 51] Loss: 1.9755 | Acc: 27.33%
           Val Loss: 1.9649 | Acc: 28.02%
[Epoch 52] Loss: 1.9689 | Acc: 27.55%
           Val Loss: 1.9581 | Acc: 28.41%
[Epoch 53] Loss: 1.9634 | Acc: 28.54%
           Val Loss: 1.9597 | Acc: 29.25%
[Epoch 54] Loss: 1.9773 | Acc: 27.22%
           Val Loss: 1.9697 | Acc: 29.67%
[Epoch 55] Loss: 1.9768 | Acc: 26.70%
           Val Loss: 1.9687 | Acc: 25.12%
[Epoch 56] Loss: 1.9661 | Acc: 27.89%
           Val Loss: 1.9627 | Acc: 28.05%
[Epoch 57] Loss: 1.9823 | Acc: 26.30%
           Val Loss: 1.9645 | Acc: 28.56%
[Epoch 58] Loss: 1.9713 | Acc: 28.60%
           Val Loss: 1.9589 | Acc: 29.12%
[Epoch 59] Loss: 1.9617 | Acc: 29.57%
           Val Loss: 1.9576 | Acc: 28.80%
[Epoch 60] Loss: 1.9627 | Acc: 29.00%
           Val Loss: 1.9551 | Acc: 29.37%
[Epoch 61] Loss: 1.9592 | Acc: 29.95%
           Val Loss: 1.9516 | Acc: 30.64%
[Epoch 62] Loss: 1.9619 | Acc: 29.68%
           Val Loss: 1.9554 | Acc: 31.16%
[Epoch 63] Loss: 1.9876 | Acc: 26.56%
           Val Loss: 1.9742 | Acc: 28.68%
[Epoch 64] Loss: 1.9700 | Acc: 27.57%
           Val Loss: 1.9577 | Acc: 29.73%
[Epoch 65] Loss: 1.9650 | Acc: 28.67%
           Val Loss: 1.9521 | Acc: 30.87%
[Epoch 66] Loss: 1.9595 | Acc: 30.34%
           Val Loss: 1.9467 | Acc: 31.79%
[Epoch 67] Loss: 1.9533 | Acc: 30.52%
           Val Loss: 1.9493 | Acc: 30.14%
[Epoch 68] Loss: 1.9506 | Acc: 30.27%
           Val Loss: 1.9417 | Acc: 31.53%
[Epoch 69] Loss: 1.9440 | Acc: 31.63%
           Val Loss: 1.9392 | Acc: 30.43%
[Epoch 70] Loss: 1.9512 | Acc: 27.91%
           Val Loss: 1.9448 | Acc: 32.17%
[Epoch 71] Loss: 1.9490 | Acc: 29.62%
           Val Loss: 1.9387 | Acc: 30.65%
[Epoch 72] Loss: 1.9444 | Acc: 30.91%
           Val Loss: 1.9385 | Acc: 31.08%
[Epoch 73] Loss: 1.9417 | Acc: 31.42%
           Val Loss: 1.9395 | Acc: 30.86%
[Epoch 74] Loss: 1.9455 | Acc: 31.49%
           Val Loss: 1.9402 | Acc: 31.89%
[Epoch 75] Loss: 1.9410 | Acc: 32.29%
           Val Loss: 1.9363 | Acc: 32.25%
[Epoch 76] Loss: 1.9364 | Acc: 32.34%
           Val Loss: 1.9349 | Acc: 32.59%
[Epoch 77] Loss: 1.9406 | Acc: 32.34%
           Val Loss: 1.9313 | Acc: 33.47%
[Epoch 78] Loss: 1.9548 | Acc: 30.86%
           Val Loss: 1.9452 | Acc: 32.08%
[Epoch 79] Loss: 1.9735 | Acc: 28.65%
           Val Loss: 1.9626 | Acc: 29.68%
[Epoch 80] Loss: 1.9716 | Acc: 28.41%
           Val Loss: 1.9731 | Acc: 28.19%
[Epoch 81] Loss: 1.9829 | Acc: 27.22%
           Val Loss: 1.9759 | Acc: 24.90%
[Epoch 82] Loss: 1.9782 | Acc: 26.44%
           Val Loss: 1.9731 | Acc: 29.33%
[Epoch 83] Loss: 1.9779 | Acc: 29.08%
           Val Loss: 1.9717 | Acc: 29.01%
[Epoch 84] Loss: 1.9699 | Acc: 28.98%
           Val Loss: 1.9506 | Acc: 31.06%
[Epoch 85] Loss: 1.9686 | Acc: 26.42%
           Val Loss: 1.9619 | Acc: 27.51%
[Epoch 86] Loss: 1.9653 | Acc: 27.65%
           Val Loss: 1.9606 | Acc: 27.85%
[Epoch 87] Loss: 1.9600 | Acc: 28.70%
           Val Loss: 1.9516 | Acc: 29.63%
[Epoch 88] Loss: 1.9547 | Acc: 29.47%
           Val Loss: 1.9523 | Acc: 29.14%
[Epoch 89] Loss: 1.9529 | Acc: 30.15%
           Val Loss: 1.9440 | Acc: 31.33%
[Epoch 90] Loss: 1.9490 | Acc: 30.51%
           Val Loss: 1.9426 | Acc: 31.02%
[Epoch 91] Loss: 1.9444 | Acc: 30.96%
           Val Loss: 1.9392 | Acc: 31.26%
[Epoch 92] Loss: 1.9396 | Acc: 31.90%
           Val Loss: 1.9345 | Acc: 32.86%
[Epoch 93] Loss: 1.9355 | Acc: 32.32%
           Val Loss: 1.9322 | Acc: 33.68%
[Epoch 94] Loss: 1.9363 | Acc: 32.00%
           Val Loss: 1.9330 | Acc: 33.43%
[Epoch 95] Loss: 1.9336 | Acc: 32.73%
           Val Loss: 1.9275 | Acc: 32.96%
[Epoch 96] Loss: 1.9308 | Acc: 33.26%
           Val Loss: 1.9264 | Acc: 32.77%
[Epoch 97] Loss: 1.9243 | Acc: 33.84%
           Val Loss: 1.9250 | Acc: 33.67%
[Epoch 98] Loss: 1.9252 | Acc: 34.03%
           Val Loss: 1.9219 | Acc: 34.71%
[Epoch 99] Loss: 1.9263 | Acc: 34.42%
           Val Loss: 1.9229 | Acc: 33.98%
[Epoch 100] Loss: 1.9230 | Acc: 34.69%
           Val Loss: 1.9174 | Acc: 35.73%

Скорее всего, вам понадобится учиться очень много эпох, чтобы предсказывать что-нибудь стоящее (эпох 100...), и, вероятнее всего, придется играться с архитектурой, чтобы получить приличное качество. На семинаре на эксперименты времени нет, поэтому добаловаться можно дома - и заодно попробовать подключить эмбеддинги w2v, например.

In [101]:
train_sampler = RandomSampler(train_sentences)
train_iterator = DataLoader(train_sentences, sampler=train_sampler, batch_size=256)

val_sampler = RandomSampler(val_sentences)
val_iterator = DataLoader(val_sentences, sampler=val_sampler, batch_size=256)

X_train, X_test = train_test_split(X_scaled, test_size=0.2)

X_tensor = torch.tensor(X_train, dtype=torch.float32)
y_tensor = torch.tensor(y_train, dtype=torch.float32)

dataset = TensorDataset(X_tensor, y_tensor)
train_loader = DataLoader(dataset, batch_size=256, shuffle=True)

X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32)

dataset2 = TensorDataset(X_test_tensor, y_test_tensor)
val_loader = DataLoader(dataset, batch_size=256, shuffle=True)

In [102]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

train (model, train_loader, val_loader, optimizer, device, yweights_tensor, epochs)

[Epoch 1] Loss: 2.3552 | Acc: 13.79%
           Val Loss: 2.3421 | Acc: 15.78%
[Epoch 2] Loss: 2.3454 | Acc: 19.52%
           Val Loss: 2.3292 | Acc: 22.20%
[Epoch 3] Loss: 2.3338 | Acc: 22.98%
           Val Loss: 2.3237 | Acc: 25.94%
[Epoch 4] Loss: 2.3273 | Acc: 21.99%
           Val Loss: 2.3177 | Acc: 24.32%
[Epoch 5] Loss: 2.3213 | Acc: 20.66%
           Val Loss: 2.3135 | Acc: 20.55%
[Epoch 6] Loss: 2.3175 | Acc: 23.23%
           Val Loss: 2.3098 | Acc: 26.07%
[Epoch 7] Loss: 2.3140 | Acc: 24.17%
           Val Loss: 2.3101 | Acc: 23.66%
[Epoch 8] Loss: 2.3110 | Acc: 22.77%
           Val Loss: 2.3032 | Acc: 23.19%
[Epoch 9] Loss: 2.3049 | Acc: 23.88%
           Val Loss: 2.3014 | Acc: 21.08%
[Epoch 10] Loss: 2.3024 | Acc: 22.45%
           Val Loss: 2.2976 | Acc: 21.75%
[Epoch 11] Loss: 2.3007 | Acc: 18.97%
           Val Loss: 2.2943 | Acc: 20.17%
[Epoch 12] Loss: 2.3007 | Acc: 21.50%
           Val Loss: 2.2933 | Acc: 21.60%
[Epoch 13] Loss: 2.2988 | Acc: 20.56%
           Val Loss: 2.2918 | Acc: 22.36%
[Epoch 14] Loss: 2.2969 | Acc: 23.34%
           Val Loss: 2.2890 | Acc: 23.93%
[Epoch 15] Loss: 2.2919 | Acc: 23.78%
           Val Loss: 2.2842 | Acc: 24.63%
[Epoch 16] Loss: 2.2915 | Acc: 23.21%
           Val Loss: 2.2842 | Acc: 25.83%
[Epoch 17] Loss: 2.2864 | Acc: 25.60%
           Val Loss: 2.2769 | Acc: 26.31%
[Epoch 18] Loss: 2.2835 | Acc: 25.25%
           Val Loss: 2.2776 | Acc: 26.20%
[Epoch 19] Loss: 2.2769 | Acc: 25.44%
           Val Loss: 2.2706 | Acc: 25.78%
[Epoch 20] Loss: 2.2764 | Acc: 26.60%
           Val Loss: 2.2711 | Acc: 26.80%
[Epoch 21] Loss: 2.2765 | Acc: 24.95%
           Val Loss: 2.2676 | Acc: 25.71%
[Epoch 22] Loss: 2.2715 | Acc: 26.90%
           Val Loss: 2.2669 | Acc: 27.25%
[Epoch 23] Loss: 2.2694 | Acc: 27.68%
           Val Loss: 2.2645 | Acc: 29.14%
[Epoch 24] Loss: 2.2700 | Acc: 28.19%
           Val Loss: 2.2632 | Acc: 29.03%
[Epoch 25] Loss: 2.2672 | Acc: 28.57%
           Val Loss: 2.2615 | Acc: 28.53%
[Epoch 26] Loss: 2.2654 | Acc: 27.14%
           Val Loss: 2.2605 | Acc: 28.93%
[Epoch 27] Loss: 2.2650 | Acc: 27.18%
           Val Loss: 2.2604 | Acc: 27.93%
[Epoch 28] Loss: 2.2653 | Acc: 26.98%
           Val Loss: 2.2605 | Acc: 29.55%
[Epoch 29] Loss: 2.2638 | Acc: 28.97%
           Val Loss: 2.2571 | Acc: 30.22%
[Epoch 30] Loss: 2.2621 | Acc: 29.98%
           Val Loss: 2.2547 | Acc: 30.42%
[Epoch 31] Loss: 2.2586 | Acc: 30.27%
           Val Loss: 2.2546 | Acc: 29.46%
[Epoch 32] Loss: 2.2567 | Acc: 30.38%
           Val Loss: 2.2555 | Acc: 29.05%
[Epoch 33] Loss: 2.2566 | Acc: 28.84%
           Val Loss: 2.2512 | Acc: 28.88%
[Epoch 34] Loss: 2.2538 | Acc: 28.84%
           Val Loss: 2.2502 | Acc: 29.67%
[Epoch 35] Loss: 2.2506 | Acc: 29.46%
           Val Loss: 2.2458 | Acc: 29.82%
[Epoch 36] Loss: 2.2511 | Acc: 29.79%
           Val Loss: 2.2466 | Acc: 30.00%
[Epoch 37] Loss: 2.2527 | Acc: 28.65%
           Val Loss: 2.2514 | Acc: 30.09%
[Epoch 38] Loss: 2.2485 | Acc: 30.29%
           Val Loss: 2.2460 | Acc: 30.10%
[Epoch 39] Loss: 2.2522 | Acc: 29.70%
           Val Loss: 2.2435 | Acc: 31.26%
[Epoch 40] Loss: 2.2505 | Acc: 31.40%
           Val Loss: 2.2489 | Acc: 32.13%
[Epoch 41] Loss: 2.2527 | Acc: 29.96%
           Val Loss: 2.2419 | Acc: 30.58%
[Epoch 42] Loss: 2.2474 | Acc: 30.27%
           Val Loss: 2.2464 | Acc: 30.10%
[Epoch 43] Loss: 2.2466 | Acc: 31.95%
           Val Loss: 2.2446 | Acc: 31.51%
[Epoch 44] Loss: 2.2520 | Acc: 30.36%
           Val Loss: 2.2488 | Acc: 28.48%
[Epoch 45] Loss: 2.2464 | Acc: 31.17%
           Val Loss: 2.2418 | Acc: 32.49%
[Epoch 46] Loss: 2.2410 | Acc: 32.42%
           Val Loss: 2.2392 | Acc: 33.23%
[Epoch 47] Loss: 2.2433 | Acc: 32.49%
           Val Loss: 2.2378 | Acc: 32.48%
[Epoch 48] Loss: 2.2410 | Acc: 31.76%
           Val Loss: 2.2352 | Acc: 31.74%
[Epoch 49] Loss: 2.2432 | Acc: 32.82%
           Val Loss: 2.2360 | Acc: 33.17%
[Epoch 50] Loss: 2.2462 | Acc: 32.47%
           Val Loss: 2.2380 | Acc: 34.52%
[Epoch 51] Loss: 2.2419 | Acc: 32.63%
           Val Loss: 2.2362 | Acc: 32.23%
[Epoch 52] Loss: 2.2392 | Acc: 33.02%
           Val Loss: 2.2342 | Acc: 33.25%
[Epoch 53] Loss: 2.2365 | Acc: 33.62%
           Val Loss: 2.2333 | Acc: 33.16%
[Epoch 54] Loss: 2.2333 | Acc: 33.15%
           Val Loss: 2.2346 | Acc: 32.84%
[Epoch 55] Loss: 2.2357 | Acc: 32.83%
           Val Loss: 2.2295 | Acc: 32.39%
[Epoch 56] Loss: 2.2345 | Acc: 32.77%
           Val Loss: 2.2318 | Acc: 33.87%
[Epoch 57] Loss: 2.2369 | Acc: 33.35%
           Val Loss: 2.2338 | Acc: 34.57%
[Epoch 58] Loss: 2.2353 | Acc: 32.59%
           Val Loss: 2.2286 | Acc: 34.54%
[Epoch 59] Loss: 2.2314 | Acc: 33.35%
           Val Loss: 2.2258 | Acc: 32.23%
[Epoch 60] Loss: 2.2300 | Acc: 33.28%
           Val Loss: 2.2250 | Acc: 34.20%
[Epoch 61] Loss: 2.2274 | Acc: 34.82%
           Val Loss: 2.2240 | Acc: 35.39%
[Epoch 62] Loss: 2.2332 | Acc: 32.47%
           Val Loss: 2.2273 | Acc: 32.87%
[Epoch 63] Loss: 2.2312 | Acc: 32.56%
           Val Loss: 2.2270 | Acc: 31.74%
[Epoch 64] Loss: 2.2305 | Acc: 31.83%
           Val Loss: 2.2252 | Acc: 34.02%
[Epoch 65] Loss: 2.2255 | Acc: 33.61%
           Val Loss: 2.2232 | Acc: 34.06%
[Epoch 66] Loss: 2.2279 | Acc: 34.32%
           Val Loss: 2.2231 | Acc: 34.23%
[Epoch 67] Loss: 2.2281 | Acc: 32.28%
           Val Loss: 2.2285 | Acc: 30.93%
[Epoch 68] Loss: 2.2267 | Acc: 32.02%
           Val Loss: 2.2217 | Acc: 33.18%
[Epoch 69] Loss: 2.2244 | Acc: 32.74%
           Val Loss: 2.2225 | Acc: 31.65%
[Epoch 70] Loss: 2.2230 | Acc: 32.92%
           Val Loss: 2.2212 | Acc: 34.21%
[Epoch 71] Loss: 2.2222 | Acc: 34.06%
           Val Loss: 2.2197 | Acc: 34.04%
[Epoch 72] Loss: 2.2216 | Acc: 34.54%
           Val Loss: 2.2173 | Acc: 35.58%
[Epoch 73] Loss: 2.2184 | Acc: 35.29%
           Val Loss: 2.2186 | Acc: 35.08%
[Epoch 74] Loss: 2.2206 | Acc: 34.93%
           Val Loss: 2.2185 | Acc: 35.59%
[Epoch 75] Loss: 2.2198 | Acc: 35.05%
           Val Loss: 2.2177 | Acc: 34.55%
[Epoch 76] Loss: 2.2173 | Acc: 35.77%
           Val Loss: 2.2154 | Acc: 34.39%
[Epoch 77] Loss: 2.2189 | Acc: 34.60%
           Val Loss: 2.2193 | Acc: 35.55%
[Epoch 78] Loss: 2.2229 | Acc: 34.57%
           Val Loss: 2.2205 | Acc: 34.85%
[Epoch 79] Loss: 2.2211 | Acc: 34.64%
           Val Loss: 2.2151 | Acc: 34.65%
[Epoch 80] Loss: 2.2175 | Acc: 34.27%
           Val Loss: 2.2167 | Acc: 32.44%
[Epoch 81] Loss: 2.2138 | Acc: 34.61%
           Val Loss: 2.2101 | Acc: 35.69%
[Epoch 82] Loss: 2.2194 | Acc: 34.27%
           Val Loss: 2.2172 | Acc: 34.78%
[Epoch 83] Loss: 2.2181 | Acc: 34.87%
           Val Loss: 2.2143 | Acc: 36.05%
[Epoch 84] Loss: 2.2138 | Acc: 35.79%
           Val Loss: 2.2117 | Acc: 35.48%
[Epoch 85] Loss: 2.2131 | Acc: 35.86%
           Val Loss: 2.2118 | Acc: 36.46%
[Epoch 86] Loss: 2.2143 | Acc: 34.48%
           Val Loss: 2.2154 | Acc: 32.81%
[Epoch 87] Loss: 2.2139 | Acc: 34.17%
           Val Loss: 2.2119 | Acc: 35.05%
[Epoch 88] Loss: 2.2128 | Acc: 35.62%
           Val Loss: 2.2097 | Acc: 36.91%
[Epoch 89] Loss: 2.2137 | Acc: 35.70%
           Val Loss: 2.2093 | Acc: 35.23%
[Epoch 90] Loss: 2.2119 | Acc: 36.07%
           Val Loss: 2.2090 | Acc: 38.36%
[Epoch 91] Loss: 2.2086 | Acc: 36.21%
           Val Loss: 2.2064 | Acc: 36.20%
[Epoch 92] Loss: 2.2113 | Acc: 35.89%
           Val Loss: 2.2055 | Acc: 34.89%
[Epoch 93] Loss: 2.2124 | Acc: 35.61%
           Val Loss: 2.2127 | Acc: 36.05%
[Epoch 94] Loss: 2.2171 | Acc: 34.54%
           Val Loss: 2.2140 | Acc: 36.74%
[Epoch 95] Loss: 2.2133 | Acc: 35.58%
           Val Loss: 2.2104 | Acc: 35.04%
[Epoch 96] Loss: 2.2102 | Acc: 36.29%
           Val Loss: 2.2063 | Acc: 38.08%
[Epoch 97] Loss: 2.2112 | Acc: 35.30%
           Val Loss: 2.2136 | Acc: 32.80%
[Epoch 98] Loss: 2.2110 | Acc: 35.24%
           Val Loss: 2.2094 | Acc: 36.32%
[Epoch 99] Loss: 2.2081 | Acc: 36.30%
           Val Loss: 2.2050 | Acc: 37.38%
[Epoch 100] Loss: 2.2081 | Acc: 37.04%
           Val Loss: 2.2042 | Acc: 38.12%

Наверное, стоит увеличить датасет, который мы загружаем, потому что я обрезал его на 90 словах для скорости. Тем временем, мы видели, что там бывают вхождения на 20000 слов...

In [109]:
from sklearn.metrics import f1_score

def train(model, train_loader, val_loader, optimizer, device, class_weights, epochs):
    model.to(device)


    if class_weights is not None:
        class_weights = class_weights.to(device)
        loss_fn = torch.nn.CrossEntropyLoss(weight=class_weights)
    else:
        loss_fn = torch.nn.CrossEntropyLoss()

    for epoch in range(epochs):
        model.train()
        total_loss = 0
        correct = 0
        total = 0

        for X, y in train_loader:
            X, y = X.to(device), y.to(device)
            y = y.long ()

            optimizer.zero_grad()
            logits = model(X)
            loss = loss_fn(logits, y)
            loss.backward()
            optimizer.step()

            total_loss += loss.item() * X.size(0)
            preds = logits.argmax(dim=1)
            correct += (preds == y).sum().item()
            total += y.size(0)

        avg_loss = total_loss / total
        acc = correct / total * 100
        print(f"[Epoch {epoch+1}] Loss: {avg_loss:.4f} | Acc: {acc:.2f}%")

        if val_loader is not None:
            model.eval()
            val_loss = 0
            val_correct = 0
            val_total = 0

            y_true_all = []
            y_pred_all = []

            with torch.no_grad():
                for X_val, y_val in val_loader:
                    y_val = y_val.long()
                    X_val, y_val = X_val.to(device), y_val.to(device)
                    logits = model(X_val)
                    loss = loss_fn(logits, y_val)
                    val_loss += loss.item() * X_val.size(0)

                    preds = logits.argmax(dim=1)
                    val_correct += (preds == y_val).sum().item()
                    val_total += y_val.size(0)

                    y_true_all.extend(y_val.cpu().numpy())
                    y_pred_all.extend(preds.cpu().numpy())

            val_loss /= val_total
            val_acc = val_correct / val_total * 100
            f1 = f1_score(y_true_all, y_pred_all, average='weighted')

            print(f"           Val Loss: {val_loss:.4f} | Acc: {val_acc:.2f}% | F1: {f1:.4f}")

In [110]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

train (model, train_loader, val_loader, optimizer, device, yweights_tensor, epochs)

[Epoch 1] Loss: 2.2070 | Acc: 37.16%
           Val Loss: 2.2066 | Acc: 37.80% | F1: 0.3879
[Epoch 2] Loss: 2.2102 | Acc: 35.37%
           Val Loss: 2.2074 | Acc: 37.36% | F1: 0.3831
[Epoch 3] Loss: 2.2069 | Acc: 37.06%
           Val Loss: 2.2043 | Acc: 38.52% | F1: 0.3947
[Epoch 4] Loss: 2.2064 | Acc: 37.46%
           Val Loss: 2.2028 | Acc: 38.66% | F1: 0.3958
[Epoch 5] Loss: 2.2063 | Acc: 37.98%
           Val Loss: 2.2032 | Acc: 37.37% | F1: 0.3828
[Epoch 6] Loss: 2.2052 | Acc: 38.09%
           Val Loss: 2.2030 | Acc: 38.39% | F1: 0.3927
[Epoch 7] Loss: 2.2020 | Acc: 38.33%
           Val Loss: 2.2000 | Acc: 38.88% | F1: 0.3981
[Epoch 8] Loss: 2.2042 | Acc: 38.32%
           Val Loss: 2.2034 | Acc: 39.16% | F1: 0.3989
[Epoch 9] Loss: 2.2081 | Acc: 37.88%
           Val Loss: 2.2039 | Acc: 36.98% | F1: 0.3786
[Epoch 10] Loss: 2.2031 | Acc: 37.74%
           Val Loss: 2.2070 | Acc: 35.44% | F1: 0.3693
[Epoch 11] Loss: 2.2089 | Acc: 36.44%
           Val Loss: 2.2058 | Acc: 36.56% | F1: 0.3796
[Epoch 12] Loss: 2.2074 | Acc: 35.96%
           Val Loss: 2.2050 | Acc: 35.62% | F1: 0.3671
[Epoch 13] Loss: 2.2063 | Acc: 36.56%
           Val Loss: 2.2012 | Acc: 38.38% | F1: 0.3934
[Epoch 14] Loss: 2.2092 | Acc: 38.17%
           Val Loss: 2.2018 | Acc: 37.90% | F1: 0.3889
[Epoch 15] Loss: 2.2074 | Acc: 36.42%
           Val Loss: 2.2022 | Acc: 35.43% | F1: 0.3661
[Epoch 16] Loss: 2.2133 | Acc: 36.58%
           Val Loss: 2.2091 | Acc: 37.90% | F1: 0.3887
[Epoch 17] Loss: 2.2116 | Acc: 36.93%
           Val Loss: 2.2067 | Acc: 38.44% | F1: 0.3942
[Epoch 18] Loss: 2.2078 | Acc: 37.36%
           Val Loss: 2.2024 | Acc: 37.08% | F1: 0.3808
[Epoch 19] Loss: 2.2058 | Acc: 38.24%
           Val Loss: 2.2005 | Acc: 38.80% | F1: 0.3967
[Epoch 20] Loss: 2.2033 | Acc: 39.02%
           Val Loss: 2.2008 | Acc: 36.18% | F1: 0.3711
[Epoch 21] Loss: 2.2044 | Acc: 35.49%
           Val Loss: 2.2001 | Acc: 38.82% | F1: 0.3964
[Epoch 22] Loss: 2.2010 | Acc: 37.99%
           Val Loss: 2.1985 | Acc: 40.04% | F1: 0.4068
[Epoch 23] Loss: 2.1985 | Acc: 38.76%
           Val Loss: 2.1970 | Acc: 38.40% | F1: 0.3932
[Epoch 24] Loss: 2.1980 | Acc: 38.55%
           Val Loss: 2.1946 | Acc: 37.71% | F1: 0.3859
[Epoch 25] Loss: 2.1977 | Acc: 39.02%
           Val Loss: 2.1944 | Acc: 40.35% | F1: 0.4103
[Epoch 26] Loss: 2.1999 | Acc: 39.06%
           Val Loss: 2.1975 | Acc: 38.48% | F1: 0.3946
[Epoch 27] Loss: 2.1959 | Acc: 39.42%
           Val Loss: 2.1971 | Acc: 38.54% | F1: 0.3940
[Epoch 28] Loss: 2.2020 | Acc: 39.04%
           Val Loss: 2.2000 | Acc: 40.62% | F1: 0.4127
[Epoch 29] Loss: 2.1996 | Acc: 38.73%
           Val Loss: 2.1994 | Acc: 37.23% | F1: 0.3838
[Epoch 30] Loss: 2.2009 | Acc: 37.80%
           Val Loss: 2.1966 | Acc: 38.34% | F1: 0.3937
[Epoch 31] Loss: 2.1995 | Acc: 37.64%
           Val Loss: 2.1954 | Acc: 39.08% | F1: 0.3995
[Epoch 32] Loss: 2.1968 | Acc: 39.38%
           Val Loss: 2.1969 | Acc: 40.10% | F1: 0.4084
[Epoch 33] Loss: 2.2002 | Acc: 38.96%
           Val Loss: 2.1968 | Acc: 40.62% | F1: 0.4128
[Epoch 34] Loss: 2.1984 | Acc: 39.94%
           Val Loss: 2.1941 | Acc: 39.70% | F1: 0.4054
[Epoch 35] Loss: 2.1957 | Acc: 39.31%
           Val Loss: 2.1970 | Acc: 38.66% | F1: 0.3949
[Epoch 36] Loss: 2.1994 | Acc: 37.49%
           Val Loss: 2.1950 | Acc: 39.08% | F1: 0.4010
[Epoch 37] Loss: 2.1949 | Acc: 40.08%
           Val Loss: 2.1955 | Acc: 41.14% | F1: 0.4175
[Epoch 38] Loss: 2.1974 | Acc: 40.95%
           Val Loss: 2.1920 | Acc: 40.65% | F1: 0.4136
[Epoch 39] Loss: 2.1976 | Acc: 39.60%
           Val Loss: 2.2009 | Acc: 34.09% | F1: 0.3476
[Epoch 40] Loss: 2.2072 | Acc: 35.62%
           Val Loss: 2.1973 | Acc: 37.54% | F1: 0.3850
[Epoch 41] Loss: 2.2000 | Acc: 37.92%
           Val Loss: 2.1958 | Acc: 37.94% | F1: 0.3895
[Epoch 42] Loss: 2.1942 | Acc: 38.28%
           Val Loss: 2.1911 | Acc: 38.86% | F1: 0.3974
[Epoch 43] Loss: 2.1981 | Acc: 38.82%
           Val Loss: 2.1927 | Acc: 39.19% | F1: 0.4012
[Epoch 44] Loss: 2.1953 | Acc: 39.24%
           Val Loss: 2.1881 | Acc: 40.43% | F1: 0.4122
[Epoch 45] Loss: 2.1940 | Acc: 39.48%
           Val Loss: 2.1923 | Acc: 38.18% | F1: 0.3913
[Epoch 46] Loss: 2.1944 | Acc: 39.24%
           Val Loss: 2.1956 | Acc: 38.26% | F1: 0.3968
[Epoch 47] Loss: 2.1980 | Acc: 37.25%
           Val Loss: 2.1945 | Acc: 37.99% | F1: 0.3939
[Epoch 48] Loss: 2.1983 | Acc: 36.33%
           Val Loss: 2.1937 | Acc: 35.63% | F1: 0.3646
[Epoch 49] Loss: 2.2000 | Acc: 36.13%
           Val Loss: 2.1922 | Acc: 37.36% | F1: 0.3848
[Epoch 50] Loss: 2.1935 | Acc: 37.89%
           Val Loss: 2.1915 | Acc: 38.06% | F1: 0.3901
[Epoch 51] Loss: 2.1895 | Acc: 39.55%
           Val Loss: 2.1867 | Acc: 40.25% | F1: 0.4108
[Epoch 52] Loss: 2.1875 | Acc: 40.36%
           Val Loss: 2.1878 | Acc: 40.52% | F1: 0.4126
[Epoch 53] Loss: 2.1909 | Acc: 41.09%
           Val Loss: 2.1903 | Acc: 39.46% | F1: 0.4069
[Epoch 54] Loss: 2.1950 | Acc: 39.22%
           Val Loss: 2.1937 | Acc: 38.58% | F1: 0.3934
[Epoch 55] Loss: 2.1907 | Acc: 39.54%
           Val Loss: 2.1883 | Acc: 41.45% | F1: 0.4211
[Epoch 56] Loss: 2.1890 | Acc: 40.62%
           Val Loss: 2.1863 | Acc: 39.38% | F1: 0.4028
[Epoch 57] Loss: 2.1872 | Acc: 40.42%
           Val Loss: 2.1840 | Acc: 41.27% | F1: 0.4199
[Epoch 58] Loss: 2.1866 | Acc: 39.49%
           Val Loss: 2.1837 | Acc: 40.41% | F1: 0.4116
[Epoch 59] Loss: 2.1853 | Acc: 39.92%
           Val Loss: 2.1916 | Acc: 36.89% | F1: 0.3801
[Epoch 60] Loss: 2.1869 | Acc: 40.42%
           Val Loss: 2.1822 | Acc: 41.60% | F1: 0.4235
[Epoch 61] Loss: 2.1854 | Acc: 41.04%
           Val Loss: 2.1825 | Acc: 40.89% | F1: 0.4169
[Epoch 62] Loss: 2.1883 | Acc: 39.47%
           Val Loss: 2.1869 | Acc: 41.76% | F1: 0.4239
[Epoch 63] Loss: 2.1896 | Acc: 40.36%
           Val Loss: 2.1911 | Acc: 37.80% | F1: 0.3910
[Epoch 64] Loss: 2.1912 | Acc: 39.60%
           Val Loss: 2.1918 | Acc: 37.65% | F1: 0.3875
[Epoch 65] Loss: 2.1906 | Acc: 39.49%
           Val Loss: 2.1889 | Acc: 40.74% | F1: 0.4160
[Epoch 66] Loss: 2.1915 | Acc: 40.45%
           Val Loss: 2.1898 | Acc: 40.73% | F1: 0.4165
[Epoch 67] Loss: 2.1902 | Acc: 38.32%
           Val Loss: 2.1927 | Acc: 36.35% | F1: 0.3712
[Epoch 68] Loss: 2.1905 | Acc: 39.20%
           Val Loss: 2.1892 | Acc: 41.14% | F1: 0.4190
[Epoch 69] Loss: 2.1917 | Acc: 40.14%
           Val Loss: 2.1876 | Acc: 39.51% | F1: 0.4036
[Epoch 70] Loss: 2.1893 | Acc: 39.24%
           Val Loss: 2.1845 | Acc: 40.40% | F1: 0.4128
[Epoch 71] Loss: 2.1886 | Acc: 39.99%
           Val Loss: 2.1883 | Acc: 40.35% | F1: 0.4105
[Epoch 72] Loss: 2.1909 | Acc: 38.92%
           Val Loss: 2.1883 | Acc: 39.44% | F1: 0.4050
[Epoch 73] Loss: 2.1888 | Acc: 40.15%
           Val Loss: 2.1864 | Acc: 39.47% | F1: 0.4061
[Epoch 74] Loss: 2.1863 | Acc: 40.26%
           Val Loss: 2.1892 | Acc: 39.92% | F1: 0.4088
[Epoch 75] Loss: 2.1889 | Acc: 39.53%
           Val Loss: 2.1827 | Acc: 41.79% | F1: 0.4242
[Epoch 76] Loss: 2.1868 | Acc: 41.66%
           Val Loss: 2.1848 | Acc: 40.93% | F1: 0.4166
[Epoch 77] Loss: 2.1849 | Acc: 40.87%
           Val Loss: 2.1823 | Acc: 41.23% | F1: 0.4197
[Epoch 78] Loss: 2.1907 | Acc: 41.04%
           Val Loss: 2.1884 | Acc: 42.31% | F1: 0.4287
[Epoch 79] Loss: 2.1922 | Acc: 40.48%
           Val Loss: 2.1836 | Acc: 41.25% | F1: 0.4206
[Epoch 80] Loss: 2.1862 | Acc: 41.67%
           Val Loss: 2.1825 | Acc: 41.55% | F1: 0.4231
[Epoch 81] Loss: 2.1838 | Acc: 41.46%
           Val Loss: 2.1820 | Acc: 41.67% | F1: 0.4245
[Epoch 82] Loss: 2.1859 | Acc: 41.37%
           Val Loss: 2.1822 | Acc: 40.74% | F1: 0.4170
[Epoch 83] Loss: 2.1814 | Acc: 41.25%
           Val Loss: 2.1823 | Acc: 40.69% | F1: 0.4148
[Epoch 84] Loss: 2.1874 | Acc: 38.87%
           Val Loss: 2.1837 | Acc: 39.40% | F1: 0.4038
[Epoch 85] Loss: 2.1835 | Acc: 41.16%
           Val Loss: 2.1826 | Acc: 42.02% | F1: 0.4277
[Epoch 86] Loss: 2.1833 | Acc: 39.69%
           Val Loss: 2.1889 | Acc: 40.24% | F1: 0.4150
[Epoch 87] Loss: 2.1881 | Acc: 40.79%
           Val Loss: 2.1855 | Acc: 39.65% | F1: 0.4077
[Epoch 88] Loss: 2.1879 | Acc: 39.17%
           Val Loss: 2.1827 | Acc: 40.53% | F1: 0.4153
[Epoch 89] Loss: 2.1841 | Acc: 40.97%
           Val Loss: 2.1797 | Acc: 40.70% | F1: 0.4161
[Epoch 90] Loss: 2.1813 | Acc: 41.40%
           Val Loss: 2.1786 | Acc: 41.96% | F1: 0.4269
[Epoch 91] Loss: 2.1823 | Acc: 40.77%
           Val Loss: 2.1812 | Acc: 41.25% | F1: 0.4208
[Epoch 92] Loss: 2.1830 | Acc: 40.65%
           Val Loss: 2.1789 | Acc: 42.37% | F1: 0.4305
[Epoch 93] Loss: 2.1801 | Acc: 41.25%
           Val Loss: 2.1775 | Acc: 41.53% | F1: 0.4238
[Epoch 94] Loss: 2.1765 | Acc: 41.63%
           Val Loss: 2.1812 | Acc: 39.53% | F1: 0.4035
[Epoch 95] Loss: 2.1818 | Acc: 40.40%
           Val Loss: 2.1787 | Acc: 41.01% | F1: 0.4195
[Epoch 96] Loss: 2.1816 | Acc: 40.56%
           Val Loss: 2.1768 | Acc: 41.83% | F1: 0.4269
[Epoch 97] Loss: 2.1807 | Acc: 41.55%
           Val Loss: 2.1762 | Acc: 42.07% | F1: 0.4278
[Epoch 98] Loss: 2.1811 | Acc: 41.68%
           Val Loss: 2.1825 | Acc: 41.32% | F1: 0.4239
[Epoch 99] Loss: 2.1822 | Acc: 41.40%
           Val Loss: 2.1803 | Acc: 39.51% | F1: 0.4062
[Epoch 100] Loss: 2.1814 | Acc: 41.23%
           Val Loss: 2.1794 | Acc: 41.07% | F1: 0.4191